### ISSUE TITLE
Uses deprecated support feature

### ISSUE THREAD

**Issue by dsvirdiau** [bremor/bonaire_myclimate#31]
My home assistant logs logged this warning. I'm attaching the warning given by HA

Entity None (<class 'custom_components.bonaire_myclimate.climate.BonaireMyClimateClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature: 0>, please create a bug report at https://github.com/bremor/bonaire_myclimate/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by boc-the-git** [comment]
Should be resolved by https://github.com/bremor/bonaire_myclimate/pull/33

**Comment by dsvirdiau** [comment]
Thank you. 🙏👌
