### ISSUE TITLE
Continued support for this repository?

### ISSUE THREAD

**Issue by boc-the-git** [bremor/bonaire_myclimate#36]
I've tried reaching out to @bremor by other means, but am putting an issue on Github to have it somewhere public too.

My understanding (though I haven't received a response from him) is that real life has got in the way of Brendan maintain this (and other) repos - which is perfectly understandable!

An excerpt of what I've sent to him privately:
> I’m a long term user of the Bonaire integration you wrote, and would be keen to take over the repository and allow it to live on, assuming you don’t have the time to do so. This is me: [Upcoming deprecations in 2025.1 · Issue #32 · bremor/bonaire_myclimate · GitHub](https://github.com/bremor/bonaire_myclimate/issues/32)
>
> I’ll probably fork the repo at some point if I don’t hear back from you, but it’s my preference not to do that, I’d rather just be added as a maintainer on your repo and we keep that alive.

**Comment by Daralm** [comment]
My whole house is automated except the bonair heater. Damn proprietary capitalism.

**Comment by bremor** [comment]
Hey @boc-the-git . Thanks for your patience with me! I have added you as a collaborator to this project. Best of luck and thanks for your help.

**Comment by boc-the-git** [comment]
Thanks @bremor, appreciate the faith.
I'll give the repo some time over the coming weeks and prioritise the upcoming deprecation notices.

**Comment by boc-the-git** [comment]
@Daralm you mention some issues? What problems are you facing? 
Can you please raise them as an issue on the repo? (Not in reply here)

**Comment by boc-the-git** [comment]
~Actually @bremor, having a closer look at things, I don't have write access to the repo, so I wouldn't be able to actually merge PRs etc.~

Scratch that.. I had an email in my inbox I had to "accept" before I got the permissions.. :facepalm:
